### ISSUE TITLE
[Question] Why 3 different MCUs?

### ISSUE THREAD

**Issue by thanhminhmr** [o7-machinehum/Protectli-UPS-Firmware#2]
I came here from the video, and I have a question about the design decision around the software/control part. I read the code and looked at the schematic already but I did not find any reason to use 3 different MCUs. Why do you opted for 3 different MCUs?

**Comment by o7-machinehum** [comment]
Hey thanks :)

The TI BQ76920pw battery manager needs a companion to set it up. The MCU needs to be on a bus created by the bq76920 so that when a fault occurs, the MCU can do something reasonable to clear the fault before the entire system power has been cut out. This MCU must be completely isolated from the rest of the system (IO and power). Additionally, this bus is 3.3V at 90mA, which isn't enough for the RP2040. 

The ESP32 is a "user-facing" component, meaning the user can fearlessly flash this device without harming the core functionality of the UPS. The ESP32 can be safely removed if the user doesn't need a screen, WiFi or NUT.
